thisset = {"apple", "banana", "cherry"}
# print(thisset)
# myset={"apple","banana","cherry",True,1,2}
# print(myset)
# print(len(myset))
# print(type(thisset))
thisset.add("orange")
print(thisset)
thisset.update("grapes")
print(thisset)
thisset.remove("banana")
print(thisset)
thisset.discard("cherry")
print(thisset)
thisset.pop("apple")
print(thisset)